---
title: "R-workshop Schedule"
output: html_document
---
<br> 

#MODULE 1: Introduction to R

##1) What is R and what are its virtues?
**[Fill this in]**


##2) Basic building blocks of R
###Presentation 1: Functions, arguments and getting help
**Writing R is like writing in English**

- Anatomy of an R command
- Action and modifiers akin to function and arguments
- Illustrate the role of parentheses, equal sign, and comma
- Show when to use argument names, and when to just use positions
- Illustrate functions within functions
- Saving output as objects 

**Getting help**

- Look at the package and function documentation
- Search in www.rseek.org or Google
- QuickR
- Swirl
- Ask a friend
- Ask a stackoverflow or the R-help mailing list. But first make sure you have the latest version of R and relevant packages, and have looked for related problems on the site, and if you've done both of those and no luck, spend some time making a reproducible example!
- Meta-learning: Look at source code; form a hypothesis about what the code does and test it

###Exercise 1
1) In it's simplest form, R can be used as an interactive calculator. 
2) Functions can replace basic algebraic operators.
3) Results can be stored and reused as objects.
4) A collection of values can be stored as a vector.
5) Vectors can be created as sequences of numbers.
6) Values can be characters as well as numbers.
7) Getting help as we go along.

##3) Looking at data

###Presentation 2: Objects

* Objects are used to hold data
* Creating objects with '<-', '=' and 'assign'
* Special values
    + NA: missing value
    + Inf and -Inf: Infinit
    + NAN: Not a number
    + NULL: Object missing
* There are many different classes of objects, each with its own properties
* vectors: numeric, character, logical
* Other objects based on the vector, but differ in dimensions and data type
```{r, echo=FALSE, message=FALSE}
library(knitr)
r1<-c("1d", "Atomic vector", "List")
r2<-c("2d", "Matrix", "Dataframe")
r3<-c("nd", "Array", "")
datstruct<-rbind( r1, r2, r3)
row.names(datstruct)<-NULL
colnames(datstruct)<-c("Dimensions", "Homogeneous", "Hetergeneous")
kable(datstruct)
```
* Go into detail on each data type?

###Exercise 2: Looking at data
1) Creating matrices and dataframes.
2) Reading in data: txt and csv.
3) Looking at data:
+ (ls)
+ class()
+ dim()
+ ncol()
+ names()
+ head()
+ summary()
+ str()
4) Missing values.
5) Subsetting vectors, matrics and dataframes.

<br> 

#MODULE 2: R for analysis and graphing
##Presentation 3: Stats and graphing
###Exercise 3: Simple statistics
**[Show basic analyses with data are that are subset/formatted correct]**

###Excercise 4: Graphing with ggplot2
**[Show basic graphs with data that are subset/formatted correct]**

**[Relate each graphing type to the type of analysis, ie ANOVA vs regression]**

##Presentation 4: Workflows
###Exercise 5:  dplyr
 - The pipeline
 
 - **filter:** keep rows that match a criteria

- **select**: pick columns by name

- **arrange:** reorder rows

- **mutate:** add new variables

- **summarize:** reduce variables to values

- **+ group_by**

<br>

#MODULE 3: R for data cleaning and storage
##Presentation 4: tidy data 
**Data that are easy to transform, visualize and model**

**Key idea: Store variables in a consistent way:**

- Each variable forms a column
- Each observation forms a row
- Each type of observational unit forms a table

**The five most common problems with messy data:**

- Multiple types of observational units are stored in the same table
- Column headers are values, not variable names
- Multiple variables are stored in one column
- Variables are stored in both rows and columns
- A single observational unit is stored in multiple tables

###Exercise 5: tidyr
- **Gather:** convert many columns into variable/value pairs; akin to melt in reshape

- **Spread:** convert variable/value pairs into columns; akin to cast in reshape

- **Separate:** break one column into two (similar to strsplit)

###Exercise 6: Linking R with data storage
- Excel vs csv
- SQL

<br>

#MODULE 4: Putting it all together: R for better monitoring and reporting
**[markdown etc]**







