---
title: "R-workshop Short Schedule"
output: word_document
---
<br> 

#MODULE 1: Introduction to R  - Monday 9:00-9:15 (JGH)

##1) What is R and what are its virtues?
**What are the advantages of R**

**What are the disadvantages of R**

##2) Introduction to the R and RStudio interface (JGH)

##3) Basic building blocks of R - Monday 9:15-10:30 (LMH)
###Presentation 1: Functions, arguments and getting help
**Writing R is like writing in English**
**Getting help**


###Exercise 1


##3) Looking at data

###Presentation 2: Objects

###Exercise 2: Looking at data

<br> 

#MODULE 2: R for analysis and graphing - Monday 1:00-4:00 (JGH, LMH)
##Presentation 3: Stats and graphing
###Exercise 3: Simple statistics
**[Show basic analyses with data are that are subset/formatted correct]**

###Excercise 4: Graphing with ggplot2
**[Show basic graphs with data that are subset/formatted correct]**

**[Relate each graphing type to the type of analysis, ie ANOVA vs regression]**

##Presentation 4: Workflows - Tuesday 8:30-10:30
###Exercise 5:  dplyr


<br>

#MODULE 3: R for data cleaning and storage  - Tuesday 10:45-noon
##Presentation 4: tidy data 
**Data that are easy to transform, visualize and model**

**Key idea: Store variables in a consistent way:**


**The five most common problems with messy data:**



###Exercise 5: tidyr



<br>

#MODULE 4: Putting it all together: R for better monitoring and reporting - 1:00-4:00
## Wrap up

 







